# Generated by Django 5.0.7 on 2024-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
