# Generated by Django 5.0.7 on 2025-08-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_teacher",
            new_name="is_online",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                ],
                default="email",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="profile_icon.png",
                null=True,
                upload_to="user/avatar/",
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=255, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="tc",
            field=models.BooleanField(default=False),
        ),
    ]
