# Generated by Django 4.1.2 on 2023-03-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Naveed', max_length=255)),
                ('standard', models.IntegerField(default=1)),
            ],
        ),
    ]
