# Generated by Django 5.0.7 on 2024-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managment", "0002_classroom_standard_student_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standard",
            name="standard",
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
