# Generated by Django 5.0.7 on 2025-08-20 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Tickets Inventory", max_length=100)),
                ("items", models.JSONField()),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(max_length=255)),
                ("deals", models.JSONField(default=list)),
            ],
        ),
    ]
